<?php
	$basic_datas = array(
			'app' 	=> '',
			'appv' 	=> '',
			'part' 	=> '',
			'sdk' 	=> '',
			'v' 	=> '',
			'uid' 	=> '',
			'ckid' 	=> '',
			'puid' 	=> '',
			'ost' 	=> '',
			'osv' 	=> '',
			'os' 	=> '',
			'dt' 	=> '',
			'jb' 	=> '',
			'sr' 	=> '',
			'ori' 	=> '',
			'gps' 	=> '',
			'net' 	=> '',
			'cc' 	=> '',
			'lang' 	=> '',
			'wmac' 	=> '',
			'dev' 	=> '',
		);
?>